# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da7c6facd410a812de8c76e4ee7e8a54cb9add0ebb16eebfaa566d629a5831f0afdb0d44f5985f028e48dfa369d59864b57636492b5ee4f390a58d1f92d8266c

test:
  secret_key_base: 015017021c55829b70028a9fb112511dbb113d5e4f6f0ea4557c70059e291b5a636836a8db948341049819d2ac1e87f9d83c98393c71e775ed9e638ca030a81d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
